import React from 'react';
import { AppConfig, AppID } from './types';
import {
  Aperture,
  UserCircle,
  IdentificationCard,
  ChatTeardrop,
  UsersThree,
  GearSix,
  Images,
  PaintBrush,
  Palette,
  Heart,
  BookOpenText,
  SealCheck,
  House,
  DeviceMobileCamera,
  Fire,
  Books,
  Question,
  GameController,
  Globe,
  PenNib,
  PiggyBank,
  Compass,
  Camera,
  Sparkle,
  GlobeSimple,
  MusicNotes,
  PhoneCall,
  Crosshair,
  Smiley,
  Brain,
  Notebook,
  Plugs,
  Newspaper,
  Planet,
  Wrench,
  HouseLine,
} from '@phosphor-icons/react';

// SVG 圖標庫 - Phosphor Icons
export const Icons: Record<string, React.FC<{ className?: string }>> = {
  Character: ({ className }) => <UserCircle className={className} weight="regular" />,
  User: ({ className }) => <IdentificationCard className={className} weight="regular" />,
  Chat: ({ className }) => <ChatTeardrop className={className} weight="regular" />,
  GroupChat: ({ className }) => <UsersThree className={className} weight="regular" />,
  Settings: ({ className }) => <GearSix className={className} weight="regular" />,
  Gallery: ({ className }) => <Images className={className} weight="regular" />,
  ThemeMaker: ({ className }) => <PaintBrush className={className} weight="regular" />,
  Appearance: ({ className }) => <Palette className={className} weight="regular" />,
  Date: ({ className }) => <Heart className={className} weight="regular" />,
  Journal: ({ className }) => <BookOpenText className={className} weight="regular" />,
  Schedule: ({ className }) => <SealCheck className={className} weight="regular" />,
  Room: ({ className }) => <House className={className} weight="regular" />,
  CheckPhone: ({ className }) => <DeviceMobileCamera className={className} weight="regular" />,
  Social: ({ className }) => <Fire className={className} weight="regular" />,
  Moments: ({ className }) => <Aperture className={className} weight="regular" />,
  Study: ({ className }) => <Books className={className} weight="regular" />,
  FAQ: ({ className }) => <Question className={className} weight="regular" />,
  Game: ({ className }) => <GameController className={className} weight="regular" />,
  Worldbook: ({ className }) => <Globe className={className} weight="regular" />,
  Novel: ({ className }) => <PenNib className={className} weight="regular" />,
  Bank: ({ className }) => <PiggyBank className={className} weight="regular" />,
  XhsFreeRoam: ({ className }) => <Compass className={className} weight="regular" />,
  XhsStock: ({ className }) => <Camera className={className} weight="regular" />,
  SpecialMoments: ({ className }) => <Sparkle className={className} weight="regular" />,
  Browser: ({ className }) => <GlobeSimple className={className} weight="regular" />,
  Songwriting: ({ className }) => <MusicNotes className={className} weight="regular" />,
  Music: ({ className }) => <MusicNotes className={className} weight="regular" />,
  Call: ({ className }) => <PhoneCall className={className} weight="regular" />,
  Guidebook: ({ className }) => <Crosshair className={className} weight="regular" />,
  LifeSim: ({ className }) => <Smiley className={className} weight="regular" />,
  MemoryPalace: ({ className }) => <Brain className={className} weight="regular" />,
  Handbook: ({ className }) => <Notebook className={className} weight="regular" />,
  QQBridge: ({ className }) => <Plugs className={className} weight="regular" />,
  HotNews: ({ className }) => <Newspaper className={className} weight="regular" />,
  VRWorld: ({ className }) => <Planet className={className} weight="regular" />,
  CharCreatorDev: ({ className }) => <Wrench className={className} weight="regular" />,
  WorldHome: ({ className }) => <HouseLine className={className} weight="regular" />,
};

export const INSTALLED_APPS: AppConfig[] = [
  { id: AppID.Character, name: '神經鏈接', icon: 'Character', color: 'indigo' },
  { id: AppID.MemoryPalace, name: '記憶宮殿', icon: 'MemoryPalace', color: 'violet' },
  { id: AppID.ChatHub, name: 'Message', icon: 'Chat', color: 'green' },
  { id: AppID.Call, name: '電話', icon: 'Call', color: 'emerald' },
  { id: AppID.GroupChat, name: '群聊', icon: 'GroupChat', color: 'violet' },
  { id: AppID.Room, name: '小小窩', icon: 'Room', color: 'rose' },
  // 家園不再做獨立桌面圖標，改從「小小窩 · 像素家園」裡進入（openApp(AppID.WorldHome) 仍可渲染）
  // { id: AppID.WorldHome, name: '家園', icon: 'WorldHome', color: 'emerald' },
  { id: AppID.CheckPhone, name: '查手機', icon: 'CheckPhone', color: 'slate' },
  // { id: AppID.Browser, name: '瀏覽器', icon: 'Browser', color: 'blue' }, // Hidden
  { id: AppID.Date, name: '見面', icon: 'Date', color: 'pink' },
  { id: AppID.User, name: '檔案', icon: 'User', color: 'blue' },
  { id: AppID.Bank, name: '存錢罐', icon: 'Bank', color: 'lime' }, // Hidden
  { id: AppID.Journal, name: '交換日記', icon: 'Journal', color: 'amber' },
  // { id: AppID.Handbook, name: '手帳', icon: 'Handbook', color: 'fuchsia' }, // Hidden temporarily, pending update
  { id: AppID.Social, name: 'Spark', icon: 'Social', color: 'red' },
  { id: AppID.Moments, name: '朋友圈', icon: 'Moments', color: 'green' },
  { id: AppID.Study, name: '自習室', icon: 'Study', color: 'emerald' },
  { id: AppID.Game, name: 'TRPG', icon: 'Game', color: 'orange' },
  { id: AppID.Novel, name: '筆友會', icon: 'Novel', color: 'amber' },
  { id: AppID.Songwriting, name: '寫歌', icon: 'Songwriting', color: 'fuchsia' },
  { id: AppID.VRWorld, name: '彼方', icon: 'VRWorld', color: 'indigo' },
  { id: AppID.Schedule, name: '時光契約', icon: 'Schedule', color: 'cyan' },
  { id: AppID.Worldbook, name: '世界書', icon: 'Worldbook', color: 'indigo' },
  { id: AppID.HotNews, name: '熱點', icon: 'HotNews', color: 'red' },
  { id: AppID.FAQ, name: '使用幫助', icon: 'FAQ', color: 'indigo' },
  { id: AppID.Gallery, name: '相冊', icon: 'Gallery', color: 'orange' },
  { id: AppID.XhsFreeRoam, name: '自由活動', icon: 'XhsFreeRoam', color: 'rose' },
  { id: AppID.XhsStock, name: '小紅書圖庫', icon: 'XhsStock', color: 'red' },
  { id: AppID.ThemeMaker, name: '氣泡工坊', icon: 'ThemeMaker', color: 'purple' },
  { id: AppID.Appearance, name: '外觀', icon: 'Appearance', color: 'slate' },
  { id: AppID.Settings, name: '設置', icon: 'Settings', color: 'slate' },
  { id: AppID.Guidebook, name: '攻略本', icon: 'Guidebook', color: 'slate' },
  { id: AppID.LifeSim, name: '都市人生', icon: 'LifeSim', color: 'purple' },
  { id: AppID.SpecialMoments, name: '特別時光', icon: 'SpecialMoments', color: 'pink' },
  { id: AppID.Music, name: '音樂', icon: 'Music', color: 'rose' },
  { id: AppID.CharCreatorDev, name: '捏臉·開發', icon: 'CharCreatorDev', color: 'amber' }, // 僅開發模式顯示（Launcher 過濾）
  // { id: AppID.QQBridge, name: 'QQ 橋', icon: 'QQBridge', color: 'sky' }, // Hidden temporarily
];

// 桌面上沒有圖標、但仍能從別處進去的 App。使用統計要靠這份補上中文名——
// 只查 INSTALLED_APPS 的話這些 App 會被靜默漏掉（比如「家園」是從小小窩進的）。
export const HIDDEN_APP_NAMES: Partial<Record<AppID, string>> = {
  [AppID.WorldHome]: '家園',
};

// 第三格原本是舊的沖浪 App（Social），換成單一貼文池的朋友圈；Social 退回桌面格子裡。
export const DOCK_APPS = [AppID.ChatHub, AppID.GroupChat, AppID.Moments, AppID.Settings];
