import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const dir='output/dino-garden-qa';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const shot=async name=>{await page.waitForTimeout(250);return page.screenshot({path:`${dir}/${name}.png`});};
const close=()=>page.getByRole('button',{name:'關閉面板',exact:true}).last().click();
const choose=async(name='莓莓')=>{await page.getByRole('button',{name:'恐龍',exact:true}).click();await page.getByRole('button',{name:'選擇'+name,exact:true}).click();};
const frame=async()=>{await page.waitForTimeout(220);};
try{
 await page.goto('http://127.0.0.1:5182/prototypes/dino-cafe/index.html');await page.waitForFunction(()=>window.render_game_to_text&&JSON.parse(window.render_game_to_text()).render.loaded.length===4,{timeout:60000});await frame();
 assert.equal((await state()).selected,'');assert.equal(await page.getByRole('navigation',{name:'庭院主操作'}).getByRole('button').count(),3);await shot('backyard-390');const initial=await state();assert.equal(initial.render.activities['sample-triceratops'].kind,'nap');assert.equal(initial.render.activities['sample-brachiosaurus'].kind,'leaves');
 // Actual touch picking opens the contextual inspector. No permanent selected-dinosaur tray.
 let s=await state(),starter=s.residents[0].id,p=s.render.activities[starter].screen;
 await page.touchscreen.tap(p.x,p.y);await page.waitForSelector('.clay-app[data-sheet="resident"]');await shot('resident-390');
 await page.getByRole('button',{name:'寫一句',exact:true}).click();assert.equal(await page.getByRole('combobox').count(),0);assert.equal(await page.getByRole('textbox').count(),1);await page.getByRole('textbox',{name:'正在',exact:true}).fill('等薄荷還自己一塊餅乾。');await shot('one-sentence-390');await page.getByRole('button',{name:'寫好了'}).click();
 await page.reload();await page.waitForSelector('.clay-app[data-ready="true"]');await choose();s=await state();assert.equal(s.residents.find(t=>t.id===starter).stage.text,'等薄荷還自己一塊餅乾。');
 await page.getByRole('button',{name:'換顏色',exact:true}).click();await page.getByRole('button',{name:'配色藍莓酪',exact:true}).click();await frame();await shot('paint-backyard-390');await page.getByRole('button',{name:'就用這個顏色'}).click();await choose();s=await state();assert.equal(s.residents.find(t=>t.id===starter).paint.body,'#9295bf');
 await page.getByRole('button',{name:'換顏色',exact:true}).click();await page.getByRole('button',{name:'配色可可豆',exact:true}).click();await close();assert.equal((await state()).residents.find(t=>t.id===starter).paint.body,'#9295bf');await choose();
 await page.getByRole('button',{name:'名字與管理'}).click();await page.getByLabel('固定這隻恐龍').click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).residents.find(t=>t.id===JSON.parse(window.render_game_to_text()).selected)?.fixed===true);await close();await page.evaluate(()=>window.advanceTime(4500));s=await state();const fixed=s.residents.find(t=>t.id===starter);assert.equal(s.render.activities[starter].position.x,fixed.pose.x);assert.equal(s.render.activities[starter].position.z,fixed.pose.z);
 await choose();await page.getByRole('button',{name:'名字與管理'}).click();await page.getByLabel('固定這隻恐龍').click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).residents.find(t=>t.id===JSON.parse(window.render_game_to_text()).selected)?.fixed===false);await close();
 // Every edit is a draft. Taps and rotation must not modify the saved garden.
 await choose();const beforeMove=await state();await page.getByRole('button',{name:'換個地方',exact:true}).click();await frame();s=await state();let dest=s.floorTargets.find(c=>c.available&&c.activity==='花叢');assert.ok(dest);
 await page.touchscreen.tap(dest.screen.x,dest.screen.y);await frame();await page.getByRole('button',{name:'向右轉45度'}).click();await frame();s=await state();assert.equal(s.revision,beforeMove.revision);assert.deepEqual(s.residents,beforeMove.residents);assert.equal(s.placing.pose.slotId,dest.id);await shot('draft-dino-390');
 await page.getByRole('button',{name:'取消',exact:true}).click();await frame();await frame();assert.deepEqual((await state()).residents,beforeMove.residents);assert.equal((await state()).revision,beforeMove.revision);
 // An occupied cell gets a red preview, a reason and a disabled Confirm.
 await choose();await page.getByRole('button',{name:'換個地方',exact:true}).click();await frame();s=await state();const blocked=s.floorTargets.find(c=>c.id===s.residents.find(t=>t.id!==starter).pose.slotId);await page.touchscreen.tap(blocked.screen.x,blocked.screen.y);await frame();assert.ok((await state()).draftError);assert.equal(await page.getByRole('button',{name:'確定擺放'}).isDisabled(),true);await shot('draft-blocked-390');await page.getByRole('button',{name:'取消',exact:true}).click();await frame();
 // A scene prop itself is the entry to interaction, not a textual destination list.
 s=await state();let target=s.render.propTargets.find(p=>p.kind==='flowers');await page.touchscreen.tap(target.x,target.y);await page.waitForSelector('.clay-app[data-sheet="prop"]');await shot('prop-detail-390');await page.getByRole('button',{name:'讓恐龍來玩'}).click();await page.getByRole('button',{name:'選擇莓莓',exact:true}).click();await frame();s=await state();assert.equal(s.revision,beforeMove.revision);assert.equal(s.render.activities[starter].kind,'sniff');await page.getByRole('button',{name:'確定擺放'}).click();await frame();s=await state();assert.equal(s.revision,beforeMove.revision+1);assert.equal(s.render.activities[starter].kind,'sniff');assert.equal(s.residents.find(t=>t.id===starter).stage.text,'等薄荷還自己一塊餅乾。');await shot('sniff-390');
 // Animations change head/feet/tail, never confirmed x/z/facing.
 const pose=s.residents.find(t=>t.id===starter).pose;await page.evaluate(()=>window.advanceTime(8500));s=await state();assert.equal(s.render.activities[starter].position.x,pose.x);assert.equal(s.render.activities[starter].position.z,pose.z);assert.equal(s.render.activities[starter].position.rotation,pose.rotation);
 await choose();await page.getByRole('button',{name:'換個地方',exact:true}).click();await frame();s=await state();target=s.render.propTargets.find(p=>p.kind==='picnic');await page.touchscreen.tap(target.x,target.y);await frame();assert.equal((await state()).render.activities[starter].kind,'snack');await page.getByRole('button',{name:'確定擺放'}).click();await frame();await shot('snack-390');
 // The same spatial activities are available to visiting characters; custom text is immutable.
 await page.getByRole('button',{name:'來訪',exact:true}).click();await page.getByLabel('共同擺弄',{exact:true}).click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).visits===true);await page.getByLabel('選擇來訪角色').selectOption('sample-visitor');await page.getByRole('button',{name:'請 ta 來看看'}).click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).events.at(-1).actorKind==='character');await page.getByRole('button',{name:/件新[变變]化/}).click();await shot('backyard-visit');await page.getByRole('button',{name:'還原這次改動'}).click();await close();
 // New prop cancel leaves no invisible item behind; confirmation creates it exactly once.
 s=await state();const propCount=s.props.length,propRevision=s.revision;
 await page.getByRole('button',{name:'佈置',exact:true}).click();await shot('backyard-build');await page.getByRole('button',{name:'添加小水窪'}).click();await frame();assert.equal((await state()).props.length,propCount);await page.getByRole('button',{name:'向右轉45度'}).click();await shot('draft-prop-390');await page.getByRole('button',{name:'取消',exact:true}).click();await frame();await frame();assert.equal((await state()).props.length,propCount);assert.equal((await state()).revision,propRevision);
 await page.getByRole('button',{name:'佈置',exact:true}).click();await page.getByRole('button',{name:'添加小水窪'}).click();await frame();assert.equal((await state()).draftError,'');await page.getByRole('button',{name:'確定擺放'}).click();await frame();s=await state();assert.equal(s.props.length,propCount+1);assert.equal(s.revision,propRevision+1);const added=s.props.find(p=>p.kind==='puddle');
 // Existing prop edits are cancellable and keep identity after confirmation.
 target=s.render.propTargets.find(p=>p.id===added.id);await page.touchscreen.tap(target.x,target.y);await page.waitForSelector('.clay-app[data-sheet="prop"]');await page.getByRole('button',{name:'調整位置和朝向'}).click();await frame();await page.getByRole('button',{name:'向右轉45度'}).click();await page.getByRole('button',{name:'取消',exact:true}).click();await frame();assert.deepEqual((await state()).props.find(p=>p.id===added.id),added);
 await page.reload();await page.waitForSelector('.clay-app[data-ready="true"]');s=await state();assert.deepEqual(s.props.find(p=>p.id===added.id),added);
 // Move a dinosaur to the new water toy via its scene affordance.
 target=s.render.propTargets.find(p=>p.id===added.id);await page.touchscreen.tap(target.x,target.y);await page.waitForSelector('.clay-app[data-sheet="prop"]');await page.getByRole('button',{name:'讓恐龍來玩'}).click();await page.getByRole('button',{name:'選擇莓莓',exact:true}).click();await frame();assert.equal((await state()).draftError,'');await page.getByRole('button',{name:'確定擺放'}).click();await page.evaluate(()=>window.advanceTime(2000));await shot('splash-390');assert.equal((await state()).render.activities[starter].kind,'splash');
 // Regression: original off-grid stumps were completely unusable through “讓恐龍來玩”.
 await frame();s=await state();const beforeStump=s;target=s.render.propTargets.find(p=>p.id==='stump-a');await page.touchscreen.tap(target.x,target.y);await page.waitForSelector('.clay-app[data-sheet="prop"]');await page.getByRole('button',{name:'讓恐龍來玩'}).click();await frame();assert.equal(await page.getByRole('button',{name:'選擇咕嚕',exact:true}).isDisabled(),true);await shot('play-options-390');await page.getByRole('button',{name:'選擇莓莓',exact:true}).click();await frame();s=await state();assert.equal(s.placing.companionProp.id,'stump-a');assert.equal(s.render.activities[starter].kind,'perch');assert.ok(s.render.activities[starter].position.y>.5);assert.deepEqual(s.props,beforeStump.props);assert.deepEqual(s.residents,beforeStump.residents);await shot('paired-play-390');
 await page.getByRole('button',{name:'取消',exact:true}).click();await frame();assert.deepEqual((await state()).props,beforeStump.props);assert.equal((await state()).revision,beforeStump.revision);
 s=await state();target=s.render.propTargets.find(p=>p.id==='stump-a');await page.touchscreen.tap(target.x,target.y);await page.waitForSelector('.clay-app[data-sheet="prop"]');await page.getByRole('button',{name:'讓恐龍來玩'}).click();await page.getByRole('button',{name:'選擇莓莓',exact:true}).click();await frame();await page.getByRole('button',{name:'確定擺放'}).click();await frame();s=await state();assert.equal(s.render.activities[starter].kind,'perch');assert.deepEqual(s.residents.filter(t=>t.id!==starter),beforeStump.residents.filter(t=>t.id!==starter));assert.deepEqual(s.props.filter(p=>p.id!=='stump-a'),beforeStump.props.filter(p=>p.id!=='stump-a'));await shot('stump-fixed-390');await page.reload();await page.waitForSelector('.clay-app[data-ready="true"]');assert.equal((await state()).render.activities[starter].kind,'perch');
 // Three maps, catalog, mobile/landscape and touch orbit remain usable.
 for(const [from,to,name] of [['溪邊草原','貝殼海岸','coast'],['貝殼海岸','火山探險','volcano']]){await page.getByRole('button',{name:from+' ⌄',exact:true}).click();await page.getByRole('button',{name:new RegExp(to)}).click();await frame();await shot('backyard-'+name);assert.equal((await state()).maps.length,3);assert.ok((await state()).maps.every(m=>m.count<=6));}
 await page.getByRole('button',{name:'恐龍',exact:true}).click();await page.getByRole('button',{name:/打[开開][图圖][鉴鑑]/}).click();await shot('backyard-catalog');
 for(const name of ['霸王龍','三角龍','劍龍','腕龍','迅猛龍','棘龍','甲龍','副櫛龍','無齒翼龍','蛇頸龍','恐龍蛋','恐龍骨架']){await page.getByRole('button',{name:new RegExp('^'+name+' ')}).click();await frame();assert.equal((await state()).render.loaded.length,1);await close();}
 await page.getByRole('button',{name:'恐龍',exact:true}).click();await close();
 await page.getByRole('button',{name:'火山探險 ⌄'}).click();await page.getByRole('button',{name:/溪[边邊]草原/}).click();
 for(const size of [{width:320,height:740},{width:844,height:390}]){await page.setViewportSize(size);await frame();await shot(`backyard-${size.width}`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),size.width);await choose();await frame();await shot(`resident-${size.width}`);const box=await page.getByRole('dialog',{name:'恐龍小日常',exact:true}).boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=size.width+1&&box.y+box.height<=size.height+1);await page.getByRole('button',{name:'換個地方',exact:true}).click();await frame();await shot(`draft-${size.width}`);const panel=await page.getByRole('region',{name:'擺放預覽'}).boundingBox();assert.ok(panel.x>=0&&panel.y>=0&&panel.x+panel.width<=size.width+1&&panel.y+panel.height<=size.height+1);await page.getByRole('button',{name:'取消',exact:true}).click();await frame();}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'還原視角'}).click();await frame();s=await state();const touch=await page.context().newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:400}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:240,y:420}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await frame();assert.notEqual((await state()).render.azimuth,s.render.azimuth);
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>window.advanceTime(500));const still=(await state()).render.activities;await page.evaluate(()=>window.advanceTime(5000));assert.deepEqual(Object.fromEntries(Object.entries((await state()).render.activities).map(([id,a])=>[id,a.position])),Object.fromEntries(Object.entries(still).map(([id,a])=>[id,a.position])));
 await fs.writeFile(`${dir}/backyard-state.json`,JSON.stringify({state:await state(),errors},null,2));assert.deepEqual(errors,[]);console.log('Draft placement/cancel/invalid/confirm, scene prop picking and stationary distinct actions. Backyard: mobile guide, touch picking, sentence save, paint/cancel, fixed poses, interaction placement, visit/undo, props, 12 models and responsive layouts passed.');
} catch(e){await shot('backyard-failure');throw e;} finally{if(errors.length)console.log(errors);await browser.close();}
