import { SARFacilityGuide } from '../SARFacilityGuide';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import type { CharacterProfile,UserProfile } from '../../../types';
import { FISHING_MARKET_STORAGE_KEY,mutateFishingMarket,readFishingMarketState,listMarketActors,marketActorName,type FishingMarketState } from '../../../utils/vrWorld/fishingMarket';
import { ensureDinosaurGarden,syncGardenToys,gardenResidents,gardenSlots,gardenCatchAvailable,editDino,gardenComment,setGardenMap,setGardenVisits,editGardenProp,giftDino,undoGardenVisit } from '../../../utils/vrWorld/dinosaurGarden';
import { DINO_CATALOG,DINO_PALETTES,PROP_LABELS,PROP_ACTIVITIES,defaultDinoPaint,dinoDefinition } from '../../../utils/vrWorld/dinosaurCatalog';
import { activeGardenMap,type DinoPaint,type GardenPropKind,type GardenEvent,type DinoPose } from '../../../utils/vrWorld/dinosaurTypes';
import { buildGardenActivities,gardenActivityAt,gardenStory } from '../../../utils/vrWorld/dinosaurActivities';
import { beginGardenPlacement,moveGardenPlacement,turnGardenPlacement,previewGardenPlacement,placementError,confirmGardenPlacement,planGardenPlay,type GardenPlacement } from '../../../utils/vrWorld/dinosaurPlacement';
import { INTERACTIVE_PROPS } from '../../../utils/vrWorld/dinosaurActivities';
import { PropIcon } from './PropIcon';
import { createGardenRenderer } from './renderer';
import './garden.css';

type Sheet='prop'|'resident'|'collection'|'paint'|'stage'|'theme'|'props'|'visits'|'history'|'profile'|'details'|null;
interface Props {userProfile:UserProfile;characters:CharacterProfile[];onClose:()=>void;onCharacterTrip:(char:CharacterProfile)=>Promise<{ok:boolean;reason?:string}>;demo?:boolean}
const stamp=(at:number)=>new Date(at).toLocaleString(undefined,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
import { DinoIcon } from './DinoIcon';
export function DinosaurGarden({userProfile,characters,onClose,onCharacterTrip,demo=false}:Props){
  const [state,setState]=useState<FishingMarketState|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState(''),[tab,setTab]=useState<'garden'|'catalog'>('garden'),[sheet,setSheet]=useState<Sheet>(null),[placing,setPlacing]=useState<GardenPlacement|null>(null);
  const [activeProp,setActiveProp]=useState(''),[playProp,setPlayProp]=useState(''),[confirmRemove,setConfirmRemove]=useState(false);
  const [paint,setPaint]=useState<DinoPaint|null>(null),[words,setWords]=useState(''),[nickname,setNickname]=useState(''),[visitor,setVisitor]=useState(''),[trip,setTrip]=useState(false),[historyPage,setHistoryPage]=useState(0),[giftTarget,setGiftTarget]=useState(''),[historyToy,setHistoryToy]=useState<string|null>(null),[focus,setFocus]=useState<{id:string;before?:DinoPose|null}|null>(null);
  const [guideStep,setGuideStep]=useState(0),[guideHidden,setGuideHidden]=useState(()=>{try{return localStorage.getItem('sar-garden-guide-v1')==='done';}catch{return false;}});
  const finishGuide=()=>{setGuideHidden(true);try{localStorage.setItem('sar-garden-guide-v1','done');}catch{/* Optional guidance preference. */}};
  const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof createGardenRenderer>|null>(null),busyRef=useRef(false),current=useRef({state,selected,placing});current.current={state,selected,placing};
  const actors=useMemo(()=>listMarketActors(userProfile,characters),[userProfile.name,characters]);
  const user=actors[0];
  const catchOwnerName=(catchId:string)=>{const caught=state?.inventory.find(c=>c.id===catchId);return caught?marketActorName(actors,caught.ownerId,caught.ownerName):'留在記錄裡的小朋友';};
  const g=state?.dinosaurGarden,map=g?activeGardenMap(g):undefined,toy=g?.toys[selected],owned=state?.inventory.filter(c=>(c.ownerId==='user'||characters.some(char=>char.id===c.ownerId))&&dinoDefinition(c.speciesId))||[],residents=state?gardenResidents(state):[];
  const activities=useMemo(()=>map?buildGardenActivities(map,residents):{},[state]);
  const activity=activities[selected];
  const draftError=state&&placing?placementError(state,placing):'';
  const previewState=useMemo(()=>state&&placing?previewGardenPlacement(state,placing):state,[state,placing]);
  const previewActivity=placing?.kind==='dino'&&previewState?buildGardenActivities(activeGardenMap(previewState.dinosaurGarden!),gardenResidents(previewState))[placing.id]:undefined;
  const prop=map?.props.find(p=>p.id===activeProp);
  const playOptions=useMemo(()=>state&&playProp?Object.fromEntries(owned.map(c=>[c.id,planGardenPlay(state,c.id,playProp)])):{},[state,playProp]);
  function beginPlacement(kind:'dino'|'prop',id:string,propKind?:GardenPropKind,nearProp=''){
    if(!state)return;
    try{
      let draft=beginGardenPlacement(state,kind,id,propKind);
      if(nearProp){const plan=planGardenPlay(state,id,nearProp);if(!plan.draft)throw new Error(plan.reason);draft=plan.draft;}
      setSelected(kind==='dino'?id:'');setPlacing(draft);setSheet(null);setTab('garden');setPaint(null);setPlayProp('');setError('');setNotice('');
    }catch(e){setError((e as Error).message);}
  }
  const cancelPlacement=()=>{setPlacing(null);setError('');setNotice('已取消，原來的佈置沒變。');};
  const confirmPlacement=()=>{if(!placing)return;const draft=placing;void commit(s=>confirmGardenPlacement(s,user,draft),'擺好了。').then(ok=>{if(ok){setPlacing(null);setGuideStep(2);}});};
  const inspect=(id:string)=>{choose(id);setTab('garden');setSheet(id?'resident':null);if(id)setGuideStep(step=>Math.max(step,1));};
  const editable=!!state&&!!toy&&gardenCatchAvailable(state,toy.catchId,state.inventory.find(c=>c.id===toy.catchId)?.ownerId),onThisMap=!!toy?.pose&&toy.mapId===g?.activeMapId,portrait=sheet==='paint'||sheet==='details';
  async function commit(change:(s:FishingMarketState)=>FishingMarketState,message?:string){if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{const next=await mutateFishingMarket(s=>change(syncGardenToys(s)));setState(next);if(message)setNotice(message);return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{busyRef.current=false;setBusy(false);}}
  const choose=(id:string)=>{setSelected(id);setPlacing(null);setPaint(null);setNotice('');};
  useEffect(()=>{let alive=true;void mutateFishingMarket(s=>ensureDinosaurGarden(s,user)).then(s=>{if(alive){setState(s);setSelected('');}}).catch(e=>{if(alive)setError(e.message);});
    const refresh=()=>{try{const next=syncGardenToys(readFishingMarketState());if(alive)setState(next);}catch(e){if(alive)setError((e as Error).message);}};
    const storage=(e:StorageEvent)=>{if(e.key===FISHING_MARKET_STORAGE_KEY)refresh();};window.addEventListener('vr-fishing-market-updated',refresh);window.addEventListener('storage',storage);
    return()=>{alive=false;window.removeEventListener('vr-fishing-market-updated',refresh);window.removeEventListener('storage',storage);};
  },[]);
  useEffect(()=>{if(!host.current)return;try{engine.current=createGardenRenderer(host.current,{ready:()=>setReady(true),error:setError,select:inspect,selectProp:id=>{setConfirmRemove(false);setActiveProp(id);setSheet('prop');setSelected('');setError('');},play:propId=>{const c=current.current;if(!c.state||c.placing?.kind!=='dino')return;const plan=planGardenPlay(c.state,c.placing.id,propId);if(plan.draft){setPlacing(plan.draft);setError('');}else setError(plan.reason);},place:pose=>{const c=current.current;if(!c.placing)return;try{setPlacing(moveGardenPlacement(c.placing,pose));setError('');}catch(e){setError((e as Error).message);}}});}catch{setError('這台設備暫時無法顯示 3D 箱庭，收藏和記錄仍可查看。');}return()=>{engine.current?.dispose();engine.current=null;};},[]);
  const sceneActive=tab==='garden'||portrait;
  useEffect(()=>{engine.current?.setActive(sceneActive);if(sceneActive&&previewState?.dinosaurGarden)void engine.current?.sync(previewState,selected,portrait?'portrait':'garden',paint||undefined,placing||undefined,!!draftError,state||undefined).then(()=>{if(focus){engine.current?.highlight(focus.id,focus.before);setFocus(null);}});},[previewState,selected,portrait,paint,focus,draftError,sceneActive]);
  useEffect(()=>{engine.current?.selectProp(sheet==='prop'?activeProp:'');},[sheet,activeProp]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{const w=window as Window&{render_game_to_text?:()=>string;advanceTime?:(ms:number)=>void};const old=w.render_game_to_text,advance=w.advanceTime;
    const render=()=>JSON.stringify({mode:'dinosaur-garden',tab,sheet,selected,placing,draftError,revision:g?.revision,mapId:g?.activeMapId,maps:g?.maps.map(m=>({id:m.id,name:m.name,count:state?gardenResidents(state,m.id).length:0})),theme:map?.theme,visits:g?.visitsEnabled,residents:residents.map(t=>({id:t.catchId,species:t.speciesId,name:t.name,paint:t.paint,pose:t.pose,stage:t.stage,fixed:t.fixed})),events:g?.events.slice(-4),render:engine.current?.metrics(),floorTargets:(state?gardenSlots(state,selected):[]).map(p=>({...p,activity:map?gardenActivityAt(map,{...p,slotId:p.id,rotation:0}).place:undefined,screen:engine.current?.project(p)})),props:map?.props});
    const step=(ms:number)=>engine.current?.advance(ms);w.render_game_to_text=render;w.advanceTime=step;
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSheet(null);setPaint(null);setPlacing(null);}if(e.target===document.body&&e.code==='Space'){e.preventDefault();engine.current?.greet();}if(e.target===document.body&&e.key==='f'){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});}};document.addEventListener('keydown',key);
    return()=>{if(w.render_game_to_text===render)w.render_game_to_text=old;if(w.advanceTime===step)w.advanceTime=advance;document.removeEventListener('keydown',key);};
  },[state,selected,placing,tab,sheet,draftError]);
  const open=(next:Sheet)=>{setPlacing(null);setPlayProp('');setWords('');setError('');if(next==='paint'&&toy)setPaint({...toy.paint});if(next==='stage'&&toy)setWords(toy.userStage.text);if(next==='profile'&&toy)setNickname(toy.name);if(next==='history')setHistoryPage(0);setSheet(next);};
  const closeSheet=()=>{setConfirmRemove(false);setPlayProp('');setSheet(null);setPaint(null);setWords('');};
  const unread=g?g.events.slice(Math.max(0,g.events.findIndex(e=>e.id===g.seenEventId)+1)).filter(e=>e.actorKind==='character'):[];
  const showHistory=(all=false)=>{setHistoryToy(all?null:selected);open('history');if(g?.events.length)void commit(s=>({...s,dinosaurGarden:{...s.dinosaurGarden!,seenEventId:g.events.at(-1)!.id}}));};
  const history=(g?.events||[]).filter(e=>!historyToy||e.toyId===historyToy||!e.toyId).slice().reverse();
  const focusEvent=(e:GardenEvent)=>{if(e.toyId){void commit(s=>setGardenMap(s,s.dinosaurGarden!.toys[e.toyId!]?.mapId||e.mapId||s.dinosaurGarden!.activeMapId)).then(ok=>{if(ok){choose(e.toyId!);setTab('garden');closeSheet();setFocus({id:e.toyId!,before:e.before?.pose});setNotice(e.summary);}});}};
  const putOnTable=()=>beginPlacement('dino',selected);
  const runVisit=async()=>{const char=characters.find(c=>c.id===visitor);if(!char||trip)return;setTrip(true);setError('');try{const result=await onCharacterTrip(char);if(!result.ok)throw new Error(result.reason==='no-api'?'請先配置角色或彼方 API':result.reason==='empty'?'這次回覆沒有給出可執行的來訪動作':result.reason==='busy'?'角色正在進行另一項活動':result.reason||'這次來訪沒有完成');setState(syncGardenToys(readFishingMarketState()));setNotice(`${char.name}來過了，看看新便籤。`);closeSheet();}catch(e){setError((e as Error).message);}finally{setTrip(false);}};
  return <main className="clay-app" data-ready={ready} data-sheet={sheet||''} data-tab={tab} data-placing={!!placing} role="dialog" aria-modal="true" aria-label="恐龍箱庭">
    <div className="clay-viewport">
    <header className="clay-header sar-facility-header"><button className="clay-back" aria-label="返回 SAR 活動室" disabled={!!placing||busy} onClick={onClose}>‹</button><div><span className="clay-eyebrow">{demo?'箱庭試玩 · 示例藏品':'SAR · CLAY DINOSAURS'}</span><h1>恐龍箱庭</h1></div><button className="clay-theme" disabled={!g||!!placing||busy} onClick={()=>open('theme')}>{map?.name||'地圖'} ⌄</button><SARFacilityGuide facility="garden"/></header>
    <div className="clay-scene" ref={host} style={{visibility:tab==='catalog'&&!portrait?'hidden':undefined}}/>
    {tab==='garden'&&!sheet&&<><div className="clay-map-caption">{residents.length} / 6 只 · {placing?'預覽中 · 確定後才會保存':'點恐龍或發亮的擺件看看'}</div><button className="clay-reset" aria-label="還原視角" onClick={()=>engine.current?.reset()}>↺</button></>}
    {placing&&<section className="clay-placement" aria-label="擺放預覽">
      <div className="clay-placement-heading"><span className="clay-preview-badge">預覽中</span><strong>{placing.kind==='prop'?PROP_LABELS[placing.propKind!]:toy?.name}{placing.companionProp?'與'+PROP_LABELS[placing.companionProp.kind]:''} · {placing.companionProp?'一起調整':'選位置和朝向'}</strong></div>
      {placing.companionProp&&<div className="clay-paired-note">這裡暫時沒有合適的互動位置，已預覽一起調整的位置。確認後才會一起挪動，取消則都留在原位。</div>}
      <p className={draftError?'is-invalid':''} role="status">{draftError|| (placing.kind==='dino'?(previewActivity?.kind!=='idle'?`放在這裡：${previewActivity?.text}`:'這裡可以安靜地待著。點發亮的擺件，試試互動位置。'):'點格子移動，箭頭是它的正面。確認前不會改變庭院。')}</p>
      <div className="clay-placement-controls"><button aria-label="向左轉45度" disabled={busy} onClick={()=>setPlacing(p=>p?turnGardenPlacement(p,-1):p)}>↶ 左轉</button><button aria-label="向右轉45度" disabled={busy} onClick={()=>setPlacing(p=>p?turnGardenPlacement(p,1):p)}>右轉 ↷</button><button disabled={busy} onClick={cancelPlacement}>取消</button><button className="clay-primary" disabled={busy||!!draftError} onClick={confirmPlacement}>{busy?'保存中…':'確定擺放'}</button></div>
    </section>}
    {!sheet&&!placing&&<nav className="clay-dock" aria-label="庭院主操作">
      <button onClick={()=>{setTab('garden');open('props');}}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V9m8 11V5m8 15V9M2 12h20M2 17h20M9 5l3-3 3 3"/></svg><span>佈置</span></button>
      <button onClick={()=>{setTab('garden');open('collection');}}><DinoIcon species="brachiosaurus" color="#7c9770"/><span>恐龍</span></button>
      <button onClick={()=>{setTab('garden');open('visits');}}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v12H9l-5 4V4Zm4 5h8M8 12h5"/></svg><span>來訪{unread.length?` · ${unread.length}`:''}</span></button>
    </nav>}
    {!ready&&!error&&<div className="clay-loading" role="status">橡皮泥小朋友正在就位…</div>}
    {(error||notice)&&<div className={'clay-toast'+(error?' is-error':'')} role={error?'alert':'status'}>{error||notice}<button aria-label="關閉提示" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
    {tab==='garden'&&!sheet&&!placing&&<>
      {!!unread.length&&<button className="clay-unread" onClick={()=>showHistory(true)}>{unread.at(-1)?.actorName}來過 · {unread.length} 件新變化 <span>看看 →</span></button>}
      {!guideHidden&&<aside className="clay-guide" aria-label="庭院小引導"><div><small>庭院小指南 · {guideStep+1} / 3</small><p>{guideStep===0?'點一隻恐龍，看看它在忙什麼。':guideStep===1?'點佈置，選個玩具。挑好位置和朝向，再點確定。':'想給它加點戲？寫一句「正在……」就好。'}</p></div><button onClick={()=>{if(guideStep===0){const id=residents[0]?.catchId;if(id)inspect(id);else open('collection');}else if(guideStep===1)open('props');else {if(!selected&&residents[0])choose(residents[0].catchId);const t=toy||residents[0];setWords(t?.userStage.text||'');setSheet(t?'stage':'collection');}}}>{guideStep===0?'看看恐龍':guideStep===1?'去佈置':'寫一句'}</button><button className="clay-guide-close" aria-label="收起引導" onClick={finishGuide}>×</button></aside>}
      {!residents.length&&<div className="clay-empty"><p>庭院還空著</p><span>從盒子裡選一隻恐龍，讓它來玩。</span><button onClick={()=>open('collection')}>選一隻恐龍</button></div>}
    </>}
    {tab==='catalog'&&!portrait&&<section className="clay-catalog"><div className="clay-section-intro"><button className="clay-text-link" onClick={()=>{setTab('garden');open('collection');}}>‹ 回到我的恐龍</button><h2>一盒橡皮泥小朋友</h2><p>已發現 {DINO_CATALOG.filter(d=>state?.discovered.includes(d.id)).length} / {DINO_CATALOG.length} 種 · 每一隻都有自己的來歷</p></div><div className="clay-species-grid">{DINO_CATALOG.map(d=>{const known=state?.discovered.includes(d.id),instances=Object.values(g?.toys||{}).filter(t=>t.speciesId===d.id),mine=owned.filter(c=>c.speciesId===d.id);return <button key={d.id} className={!known?'is-unknown':''} onClick={()=>{if(instances.length){choose(mine[0]?.id||instances[0].catchId);open('details');}else setNotice(known?'曾經發現過它，這份舊存檔沒有留下單隻記錄。':'再去水域試試運氣，也許下次就是它。');}}><DinoIcon species={d.id} color={known?d.body:'#bdc2af'}/><strong>{known?d.name:'尚未遇見'}</strong><span>{known?mine.length?`共有 ${mine.length} 只`:'曾經發現':'橡皮泥藏品'}</span></button>;})}</div></section>}
    {sheet&&<div className={'clay-sheet-wrap '+(portrait?'is-portrait':sheet==='resident'?'is-resident':sheet==='prop'?'is-prop':'')}><button className="clay-scrim" aria-label="關閉面板" onClick={closeSheet}/><section className="clay-sheet" role="dialog" aria-modal={sheet!=='resident'} aria-label={{prop:'擺件詳情',resident:'恐龍小日常',collection:'我的恐龍',paint:'恐龍換色',stage:'正在做什麼',theme:'選擇地圖',props:'桌面擺件',visits:'角色來訪',history:'箱庭足跡',profile:'這隻恐龍',details:'恐龍圖鑑詳情'}[sheet]}>
      <div className="clay-sheet-head"><h2>{{prop:prop?PROP_LABELS[prop.kind]:'擺件',resident:toy?.name||'恐龍小日常',collection:'我的恐龍',paint:'給橡皮泥換個顏色',stage:'它正在做什麼？',theme:'今天去哪裡玩？',props:'佈置庭院',visits:'讓角色來坐一會兒',history:'留在桌上的足跡',profile:toy?.name||'這隻恐龍',details:dinoDefinition(toy?.speciesId||'')?.name||'恐龍圖鑑'}[sheet]}</h2><button aria-label="關閉面板" onClick={closeSheet}>×</button></div>
      {sheet==='paint'&&paint&&toy&&<><p className="clay-muted">換身體和小細節的顏色，眼睛與表情會保留。</p><div className="clay-palettes">{DINO_PALETTES.map(p=><button key={p.name} aria-label={`配色${p.name}`} aria-pressed={p.body===paint.body&&p.accent===paint.accent} onClick={()=>setPaint({body:p.body,accent:p.accent})}><span style={{background:p.body}}><i style={{background:p.accent}}/></span>{p.name}</button>)}</div><div className="clay-colors"><label>身體<input aria-label="身體顏色" type="color" value={paint.body} onChange={e=>setPaint({...paint,body:e.target.value})}/></label><label>角、背板與細節<input aria-label="細節顏色" type="color" value={paint.accent} onChange={e=>setPaint({...paint,accent:e.target.value})}/></label><button onClick={()=>setPaint(defaultDinoPaint(toy.speciesId))}>原來的顏色</button></div><button className="clay-primary clay-wide" disabled={busy||!editable} onClick={()=>void commit(s=>editDino(s,user,selected,{paint}),'新配色保存好了。').then(ok=>{if(ok)closeSheet();})}>就用這個顏色</button></>}
      {sheet==='resident'&&toy&&<>
        <p className="clay-resident-meta">{dinoDefinition(toy.speciesId)?.name} · {catchOwnerName(selected)}的恐龍{toy.fixed?' · 已固定':''}</p>
        <div className="clay-resident-story"><small>正在{toy.stage.text&&toy.stage.byId!=='user'?` · ${toy.stage.byName}續寫`:''}</small><p>{gardenStory(toy,activity)}</p>{activity&&<span>{activity.place} · {activity.kind==='nap'?'打個盹':activity.kind==='snack'?'吃點心':activity.kind==='splash'?'玩水':activity.kind==='leaves'?'夠樹葉':activity.kind==='sniff'?'聞聞花':activity.kind==='perch'?'放哨':'看看四周'}</span>}</div>
        <div className="clay-resident-actions"><button className="clay-primary" disabled={!editable||busy||!ready} onClick={()=>beginPlacement('dino',selected)}>{onThisMap?'換個地方':toy.pose?'搬來這裡':'放進庭院'}</button><button disabled={!editable} onClick={()=>open('paint')}>換顏色</button><button disabled={!editable} onClick={()=>open('stage')}>寫一句</button></div>
        <div className="clay-resident-more"><button disabled={!onThisMap||!editable||busy} onClick={()=>beginPlacement('dino',selected)}>轉向 ↻</button><button disabled={!onThisMap} onClick={()=>engine.current?.greet()}>打招呼</button><button onClick={()=>showHistory()}>足跡</button><button onClick={()=>open('profile')}>名字與管理</button></div>
      </>}
      {sheet==='collection'&&<><p className="clay-muted">{playProp?'選一隻恐龍來玩。可以來的會標出來，確定後才搬過去。':'你和角色收集的小朋友都在這裡。每張庭院最多住 6 只。'}</p><div className="clay-collection">{owned.map(c=>{const t=g?.toys[c.id];if(!t)return null;return <button key={c.id} aria-label={`選擇${t.name}`} disabled={!!playProp&&!playOptions[c.id]?.draft} onClick={()=>playProp?beginPlacement('dino',c.id,undefined,playProp):inspect(c.id)}><DinoIcon species={c.speciesId} color={t.paint.body}/><span><strong>{t.name}</strong><small>{c.ownerId==='user'?'我的':marketActorName(actors,c.ownerId,c.ownerName)+'的'} · {dinoDefinition(c.speciesId)?.name}</small></span><em className={playProp?'clay-play-availability':undefined}>{playProp?(playOptions[c.id]?.reason||(playOptions[c.id]?.draft?.companionProp?'可以來 · 會一起調整擺件':'可以來玩')):!gardenCatchAvailable(state!,c.id,c.ownerId)?'暫不可擺放':t.pose?g?.maps.find(m=>m.id===t.mapId)?.name:'在盒子裡'}</em></button>;})}</div>{playProp&&<button className="clay-wide" onClick={()=>beginPlacement('prop',playProp)}>調整這個擺件的位置</button>}<button className="clay-wide" onClick={()=>{setTab('catalog');closeSheet();}}>打開圖鑑 · {DINO_CATALOG.filter(d=>state?.discovered.includes(d.id)).length} / {DINO_CATALOG.length}</button></>}
      {sheet==='stage'&&toy&&<><label className="clay-field clay-story-field">正在<textarea aria-label="正在" maxLength={160} value={words} placeholder={activity?.text||'等薄荷還自己一塊餅乾。'} onChange={e=>setWords(e.target.value)}/></label><p className="clay-muted">寫一句它的小劇場就好。留空時，會顯示它在這裡的小日常。</p>{toy.stage.text&&toy.stage.byId!=='user'&&<p className="clay-muted">{toy.stage.byName}後來寫過：{toy.stage.text}。舊記錄會保留。</p>}<button className="clay-primary clay-wide" disabled={busy||!editable} onClick={()=>void commit(s=>editDino(s,user,selected,{stage:{text:words}}),'這句話留在它身邊了。').then(ok=>{if(ok){finishGuide();setSheet('resident');}})}>寫好了</button></>}
      {sheet==='theme'&&<><p className="clay-muted">所有角色共用這些小地圖，每張最多 6 只。搬家會保留名字、配色與經歷。</p><div className="clay-theme-options">{g?.maps.map(m=><button key={m.id} aria-pressed={g.activeMapId===m.id} disabled={busy} onClick={()=>void commit(s=>setGardenMap(s,m.id)).then(ok=>{if(ok){setSelected('');closeSheet();engine.current?.reset();}})}><span className={`clay-landscape ${m.theme}`}/><strong>{m.name}</strong><small>{state?gardenResidents(state,m.id).length:0} / 6 只 · {m.theme==='grassland'?'小山坡與溪邊營地':m.theme==='coast'?'貝殼、淺水與海邊小屋':'圓圓的火山與探險營地'}</small></button>)}</div></>}
      {sheet==='props'&&<><p className="clay-muted">選個擺件 → 點格子找位置 → 轉向 → 確定。</p><button className="clay-text-link" onClick={()=>open('theme')}>更換庭院 · {map?.name} ›</button>
        <h3 className="clay-prop-heading">給恐龍的玩具 <small>會有小動作</small></h3>
        {[true,false].map(interactive=><React.Fragment key={String(interactive)}>{!interactive&&<h3 className="clay-prop-heading">裝點小院 <small>純裝飾</small></h3>}<div className="clay-prop-add">{Object.entries(PROP_LABELS).filter(([kind])=>INTERACTIVE_PROPS.includes(kind as GardenPropKind)===interactive).map(([kind,label])=><button key={kind} aria-label={`添加${label}`} disabled={busy||(map?.props.length||0)>=12} onClick={()=>beginPlacement('prop','',kind as GardenPropKind)}><PropIcon kind={kind as GardenPropKind}/><strong>{label}</strong><small>{PROP_ACTIVITIES[kind as GardenPropKind]}</small></button>)}</div></React.Fragment>)}
        <p className="clay-muted">已擺放 {map?.props.length} / 12 件 · 點庭院中的擺件也能調整</p><div className="clay-prop-list">{map?.props.map(p=><button key={p.id} onClick={()=>{setConfirmRemove(false);setActiveProp(p.id);setSheet('prop');}}><PropIcon kind={p.kind}/><span>{PROP_LABELS[p.kind]}</span><span>查看 ›</span></button>)}</div></>}
      {sheet==='prop'&&prop&&<><div className="clay-prop-detail"><PropIcon kind={prop.kind}/><div><strong>{INTERACTIVE_PROPS.includes(prop.kind)?'互動玩具':'庭院裝飾'}</strong><p>{PROP_ACTIVITIES[prop.kind]}</p></div></div><p className="clay-muted">{INTERACTIVE_PROPS.includes(prop.kind)?'選一隻恐龍，預覽它能玩的地方。點確定後，它就會留在那裡做小動作。':'擺在哪裡、朝向哪裡，由你來決定。它不會觸發恐龍動作。'}</p>{INTERACTIVE_PROPS.includes(prop.kind)&&<button className="clay-primary clay-wide" onClick={()=>{setPlayProp(prop.id);setSheet('collection');}}>讓恐龍來玩</button>}<div className="clay-inline"><button onClick={()=>beginPlacement('prop',prop.id)}>調整位置和朝向</button><button disabled={busy} onClick={()=>setConfirmRemove(true)}>收起擺件</button></div>{confirmRemove&&<div className="clay-remove-confirm" role="alert"><p>收起{PROP_LABELS[prop.kind]}？恐龍會留在原位。</p><div className="clay-inline"><button onClick={()=>setConfirmRemove(false)}>留著吧</button><button disabled={busy} onClick={()=>void commit(s=>editGardenProp(s,user,{id:prop.id,remove:true}),'擺件收好了，恐龍的位置保留。').then(ok=>{if(ok)closeSheet();})}>確定收起</button></div></div>}</>}
      {sheet==='visits'&&<><button className="clay-wide" onClick={()=>showHistory(true)}>看看來訪足跡{unread.length?` · ${unread.length} 件新變化`:' ›'}</button><label className="clay-toggle"><span>共同擺弄<small>允許已接入彼方的角色留便籤、挪動恐龍和續寫狀態。固定的恐龍只收便籤。</small></span><input type="checkbox" aria-label="共同擺弄" checked={!!g?.visitsEnabled} disabled={busy} onChange={e=>{const checked=e.currentTarget.checked;void commit(s=>setGardenVisits(s,checked,user));}}/></label><p className="clay-muted">自動來訪發生在彼方運行時。關閉應用期間暫不會產生新的來訪。</p><label className="clay-field">現在邀請一位<select aria-label="選擇來訪角色" value={visitor} onChange={e=>setVisitor(e.target.value)}><option value="">選擇角色</option>{characters.filter(c=>c.vrState?.enabled).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="clay-primary clay-wide" disabled={!visitor||trip||!g?.visitsEnabled||!residents.length} onClick={()=>void runVisit()}>{trip?'正在走過來看…':'請 ta 來看看'}</button><p className="clay-muted">每次邀請調用一次角色模型。自動來訪有間隔，不補刷錯過的日子。</p></>}
      {sheet==='history'&&<><div className="clay-history">{history.slice(historyPage*15,historyPage*15+15).map(e=><article key={e.id}><small>{e.actorName} · {stamp(e.at)}</small><p>{e.summary}</p>{e.words&&<blockquote>{e.words}</blockquote>}<div>{e.toyId&&<button onClick={()=>focusEvent(e)}>看看它</button>}{e.before&&e.actorKind==='character'&&g?.toys[e.toyId||'']?.revision===e.afterRevision&&!g?.events.some(n=>n.undoOf===e.id)&&<button disabled={busy} onClick={()=>void commit(s=>undoGardenVisit(s,e.id,user))}>還原這次改動</button>}</div></article>)}</div><div className="clay-pager"><button disabled={!historyPage} onClick={()=>setHistoryPage(p=>p-1)}>較新</button><span>{historyPage+1}</span><button disabled={(historyPage+1)*15>=history.length} onClick={()=>setHistoryPage(p=>p+1)}>更早</button></div><label className="clay-field">接著留一句<textarea aria-label="回應便籤" value={words} maxLength={240} onChange={e=>setWords(e.target.value)} placeholder="她贏了就是贏了。"/></label><button className="clay-primary clay-wide" disabled={busy||!words.trim()} onClick={()=>void commit(s=>gardenComment(s,user,selected||undefined,words)).then(ok=>{if(ok)setWords('');})}>留下便籤</button></>}
      {sheet==='profile'&&toy&&<><label className="clay-field">它的名字<input aria-label="恐龍名字" value={nickname} maxLength={16} onChange={e=>setNickname(e.target.value)}/></label><button className="clay-primary clay-wide" disabled={busy||!editable||!nickname.trim()} onClick={()=>void commit(s=>editDino(s,user,selected,{name:nickname})).then(ok=>{if(ok)closeSheet();})}>保存名字</button><label className="clay-toggle"><span>固定這隻<small>角色可以評論，但不能挪動或續寫它的狀態。</small></span><input aria-label="固定這隻恐龍" type="checkbox" checked={toy.fixed} disabled={busy||!editable} onChange={e=>{const fixed=e.currentTarget.checked;void commit(s=>editDino(s,user,selected,{fixed}));}}/></label><div className="clay-inline"><button onClick={()=>open('details')}>近看與來歷</button><button disabled={!editable||!toy.pose||busy} onClick={()=>void commit(s=>editDino(s,user,selected,{pose:null})).then(ok=>{if(ok)closeSheet();})}>收進盒子</button></div><label className="clay-field">送給<select aria-label="贈送給角色" value={giftTarget} onChange={e=>setGiftTarget(e.target.value)}><option value="">選擇角色</option>{characters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="clay-wide" disabled={!giftTarget||!editable||busy||state?.inventory.find(c=>c.id===selected)?.ownerId!=='user'} onClick={()=>{const c=characters.find(c=>c.id===giftTarget);if(c)void commit(s=>giftDino(s,user,selected,{id:c.id,name:c.name,kind:'character'}),'已經送給 ta，名字與經歷也一起帶過去了。').then(ok=>{if(ok)closeSheet();});}}>把這隻送給 ta</button></>}
      {sheet==='details'&&toy&&<><div className="clay-detail-name"><strong>{toy.name}</strong><span>{catchOwnerName(selected)}</span></div><p className="clay-fact">{dinoDefinition(toy.speciesId)?.fact}</p><p className="clay-muted">{toy.origin.kind==='fished'?`${marketActorName(actors,toy.origin.actorId,toy.origin.actorName)}釣到了它`:toy.origin.kind==='gift'?`${marketActorName(actors,toy.origin.actorId,toy.origin.actorName)}送出的橡皮泥模型`:'舊存檔未記錄最初的獲得者'} · {stamp(toy.origin.at)}</p><div className="clay-instances">{Object.values(g?.toys||{}).filter(t=>t.speciesId===toy.speciesId).map(t=><button aria-pressed={selected===t.catchId} key={t.catchId} onClick={()=>choose(t.catchId)}>{t.name}</button>)}</div><div className="clay-inline"><button onClick={()=>showHistory()}>這隻的足跡</button><button disabled={!editable} onClick={()=>open('paint')}>換個顏色</button>{editable&&<button className="clay-primary" disabled={busy} onClick={()=>{if(onThisMap){setTab('garden');closeSheet();}else putOnTable();}}>去箱庭</button>}</div></>}
    </section></div>}
    </div>
  </main>;
}
