#!/usr/bin/env node
// node >= 20
//
// Builds every esbuild-bundled Worker in the WORKERS manifest. Dual-output:
//   worker/<name>/worker.bundle.js   ← user copies this into the CF dashboard
//   public/<outName>                 ← vite ships to dist/, Modal fetch reads it
//
// Adding a new Worker:
//   1. drop the entry at worker/<new>/src/index.ts
//   2. add a row to WORKERS below
//   3. that's it — `pnpm run build` (which chains to build:workers) picks it up
//
// Why a manifest array instead of auto-discover: worker/proactive-push/ has
// src/index.ts + wrangler.toml too, but its worker.bundle.js is hand-written
// (not an esbuild artifact). A naive scan of worker/*/src/index.ts would
// silently overwrite it. The manifest is explicit about which workers go
// through this pipeline.

import { build } from 'esbuild';
import { existsSync, statSync, copyFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Each entry can override entry/outWorker/outPublic paths so we can bundle:
//   - per-worker dirs (worker/<name>/src/index.ts → worker/<name>/worker.bundle.js + public/<outName>)
//   - flat single-file workers (worker/<name>.ts → public/<name>.js only — no worker.bundle.js sibling)
const WORKERS = [
  // sw-keep-alive 是 SullyOS 的 service worker, 唯一消費者是瀏覽器從 /public 靜態讀, 不需要
  // CF wrangler 單獨部署 (沒 worker.bundle.js sibling). 之前 bundle 是手工跑 esbuild, Round 2
  // 起接進 build:workers 一起做, 避免 worker/sw-keep-alive.ts 跟 public/sw-keep-alive.js 漂移.
  {
    name: 'sw-keep-alive',
    entryPath: 'worker/sw-keep-alive.ts',
    outPublic: 'public/sw-keep-alive.js',
    skipWorkerOut: true,
  },
  // post-office 是純後端（跨用戶漂流信），不被前端靜態 fetch，所以只產 worker.bundle.js
  // 供粘進 CF 面板（選 ES Module 格式）或對照 wrangler deploy，不寫 public/。
  {
    name: 'post-office',
    skipPublicOut: true,
  },
  // amsg = 主動消息 2.0 的單用戶 worker（amsg-server/cloudflare, D1 + Cron Trigger）。
  // public/ 副本給設置頁「複製 Worker 代碼」按鈕 fetch。amsg-server 2.6.0-next.2 起
  // 全 Web Crypto，免 nodejs_compat flag。
  { name: 'amsg', outName: 'amsg-worker.bundle.js' },
];

// The bundled workers use only Web Crypto (globalThis.crypto.subtle) and have
// zero Node crypto imports, so they run on CF Workers with no compatibility
// flags and no runtime polyfill.
const sharedOpts = {
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  bundle: true,
  minify: false,
  conditions: ['worker', 'browser', 'import', 'default'],
  // cloudflare:* 是運行時自帶的內置模塊（amsg 用 cloudflare:workers 的 DurableObject
  // 基類）。它們不在 node_modules 裡，不標 external 的話 esbuild 會當成缺失依賴報錯。
  external: ['cloudflare:*'],
};

console.log(`Building ${WORKERS.length} worker bundle(s)...`);

for (const w of WORKERS) {
  const entry = resolve(root, w.entryPath || `worker/${w.name}/src/index.ts`);
  if (!existsSync(entry)) {
    console.error(`ERROR: entry not found for "${w.name}": ${entry}`);
    process.exit(1);
  }

  const banner = { js: `/* generated by scripts/build-workers.mjs — do not edit by hand */` };
  const outputs = [];

  let outWorker = null;
  if (!w.skipWorkerOut) {
    outWorker = resolve(root, w.outWorker || `worker/${w.name}/worker.bundle.js`);
    outputs.push(outWorker);
  }
  let outPublic = null;
  if (!w.skipPublicOut) {
    outPublic = resolve(root, w.outPublic || `public/${w.outName}`);
    outputs.push(outPublic);
  }
  if (outputs.length === 0) {
    console.error(`ERROR: "${w.name}" skips both worker and public output — nothing to build`);
    process.exit(1);
  }

  for (const out of outputs) {
    await build({ ...sharedOpts, entryPoints: [entry], outfile: out, banner });
  }

  const sizeRef = outWorker || outPublic;
  const sizeKb = (statSync(sizeRef).size / 1024).toFixed(1);
  const dest = [
    outWorker && (w.outWorker || `worker/${w.name}/worker.bundle.js`),
    outPublic && (w.outPublic || `public/${w.outName}`),
  ].filter(Boolean).join(' + ');
  console.log(`✓ ${w.name.padEnd(16)} ${sizeKb} KB  → ${dest}`);
}

// 原樣複製到 public/ 的單文件腳本（不過 esbuild）。
//
// 為什麼不打包：這些文件沒有 import，是自包含單文件，而 Deno Playground 原生吃
// TypeScript。過一遍 esbuild 只會剝掉類型、還可能順手把註釋吃了 —— 而這類腳本
// 恰恰要用戶讀著註釋改配置（比如 amsg 代理裡的 UPSTREAM 那一行），註釋沒了就廢了。
const VERBATIM_COPIES = [
  // amsg 的 Deno 門面：給 Cloudflare worker 換一個國內能直連的地址。
  // 設置頁「複製 Deno 代理代碼」按鈕 fetch 這份。
  { from: 'worker/amsg/deno-proxy.ts', to: 'public/amsg-deno-proxy.ts' },
];

for (const { from, to } of VERBATIM_COPIES) {
  const src = resolve(root, from);
  if (!existsSync(src)) {
    console.error(`ERROR: verbatim copy source not found: ${from}`);
    process.exit(1);
  }
  copyFileSync(src, resolve(root, to));
  const sizeKb = (statSync(src).size / 1024).toFixed(1);
  console.log(`✓ ${from.split('/').pop().padEnd(16)} ${sizeKb} KB  → ${to} (原樣複製)`);
}
